### ISSUE TITLE
Script completo testsim

### ISSUE THREAD

**Issue by ralvarez-hub** [ralvarez-hub/testsim#1]
Ya he subido la versión final del script del simulacro de examen. Creo que funciona.
También he subido el ambiente.
Creo que había que hacer algo más de un script que llamase a otro script, pero no entiendo muy bien a qué se refiere.

**Comment by tdido** [comment]
Hola Ruth.

El script está muy bien. Tiene un error menor, que es que te faltó un parámetro del STAR al indexar un genoma pequeño. Si te fijás, durante la indexación te aparece este warning:

```
WARNING: --genomeSAindexNbases 14 is too large for the genome size=4718592, which may cause seg-fault at the mapping step. Re-run genome generation with recommended --genomeSAindexNbases 10
```
Y eso causa este error durante el alineamiento:
```
scripts/analyse_sample.sh: line 17: 15051 Segmentation fault
```
Yo en la lección había puesto 9 en lugar de 10. Con lo cual, el comando correcto para indexar sería:
```shell
STAR --runThreadN 4 --runMode genomeGenerate --genomeDir res/genome/star_index/ --genomeFastaFiles res/genome/ecoli.fasta --genomeSAindexNbases 9
```
Con eso ya debería ejecutar todo sin errores.

En cuanto al tema de que un script llame a otro, la idea era que en lugar de expandir el script "analyse_sample.sh", crear uno llamado por ejemplo "run_pipeliene.sh" que contuviera el código nuevo, y en el for llamara al otro así:

```shell
for sampleid in $(ls data/*.fastq.gz | cut -d"_" -f1 | cut -d"/" -f2 | sort |uniq)
do
    bash scripts/analyse/sample.sh $sampleid
done
```
De todas maneras esto lo podrás ver implementado cuando suba la solución.
